### ISSUE TITLE
Slow Compilation Time

### ISSUE THREAD

**Issue by bradymwilliams** [ericwindmill/gatsby-starter-docs#1]
The console gives no indication of why, but the compilation time of site is incredibly slow.

```
success createLayouts — 0.017 s
success createPages — 0.041 s
success createPagesStatefully — 0.009 s
success extract queries from components — 0.199 s
success run graphql queries — 0.709 s
success write out page data — 0.002 s
success update schema — 0.237 s

info bootstrap finished - 3.504 s

 DONE  Compiled successfully in 63420ms
```

**Comment by ericwindmill** [comment]
@bradymwilliams It doesn't seem to be slower than other gatsby-starters: 

Material Starter:
```
success delete html files from previous builds — 0.006 s
success open and validate gatsby-config.js — 0.005 s
success copy gatsby files — 0.021 s
success onPreBootstrap — 0.006 s
success source and transform nodes — 0.100 s
success building schema — 0.325 s
success createLayouts — 0.008 s
success createPages — 0.067 s
success createPagesStatefully — 0.008 s
success onPreExtractQueries — 0.001 s
success update schema — 0.101 s
success extract queries from components — 0.104 s
success run graphql queries — 0.636 s
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 3.072 s
```



Docs Starter:
```
success delete html files from previous builds — 0.010 s
success open and validate gatsby-config.js — 0.005 s
success copy gatsby files — 0.023 s
success onPreBootstrap — 0.006 s
success source and transform nodes — 0.057 s
success building schema — 0.350 s
success createLayouts — 0.013 s
success createPages — 0.040 s
success createPagesStatefully — 0.007 s
success onPreExtractQueries — 0.001 s
success update schema — 0.103 s
success extract queries from components — 0.110 s
success run graphql queries — 0.008 s
success write out page data — 0.002 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 2.335 s
```

**Comment by ericwindmill** [comment]
Not closing this until I have an example with significant content that I can test.

**Comment by evanbreitsch** [comment]
I think I'm facing this as well. I believe @bradymwilliams is referring to the time it takes for:

> DONE  Compiled successfully in 63420ms

rather than

> info bootstrap finished - 2.335 s

I notice the page cant be refreshed until "Done Compiled..." is printed to the terminal, but I'm still not familiar with the project enough to know what is actually "Done". Regardless, 63 seconds seems like a long time for any process. Taking a look at the [issues on another Gatsby project](https://github.com/gatsbyjs/gatsby/issues/3406) it looks like the slow times are systemic to Gatsby 1, with the general guess that images add to the time till 'Done.'

**Comment by IniZio** [comment]
I am also facing same issue described by @evanbreitsch , it is a fresh scaffold.

**Comment by MichaelNeas** [comment]
Similarly my compile time out of the box was a little hefty, here are the times I get rather consistently.

```
$ gatsby develop
success open and validate gatsby-config.js — 0.019 s
success copy gatsby files — 0.058 s
success source and transform nodes — 0.147 s
success building schema — 0.838 s
success createLayouts — 0.016 s
success createPages — 0.052 s
success createPagesStatefully — 0.016 s
success extract queries from components — 0.250 s
success run graphql queries — 0.039 s
success write out page data — 0.002 s
success update schema — 0.233 s

info bootstrap finished - 5.566 s

 DONE  Compiled successfully in 131626ms          

 I  Your site is running at http://localhost:8000
 I  Your graphql debugger is running at http://localhost:8000/___graphql
 WAIT  Compiling...                     

 DONE  Compiled successfully in 5816ms      

 I  Your site is running at http://localhost:8000
 I  Your graphql debugger is running at http://localhost:8000/___graphql
```

**Comment by rafi** [comment]
I cloned this repo, `yarn install`, `gatsby develop` and it took over a minute to compile.
> DONE  Compiled successfully in 61402ms

**Comment by noetix** [comment]
Same here.

```
gatsby new https://github.com/ericwindmill/gatsby-starter-docs
gatsby develop
```

> info bootstrap finished - 5.095 s
> DONE  Compiled successfully in 76837ms

**Comment by levino** [comment]
As @ericwindmill points out: This is not an issue, but a "wontfix" as you do not **compare** your build times to other starters and prove that they are compiling faster. Until then I would say this issue should be closed as "wontfix".

**Comment by noetix** [comment]
Clearly theres an issue with webpack configuration within this starter. I don't care if you mark this as "wontfix" but the reason you've given is incorrect.

**Comment by levino** [comment]
I will make a comparison with other starters and post back.
