### ISSUE TITLE
Use single quotes and no semicolon.

### ISSUE THREAD

**Issue by levino** [ericwindmill/gatsby-starter-docs#16]
Just a suggestion:

Lets change the code style rules to singlequotes and no trailing semicolons. So this
```js
import yada from "yada";
```
becomes this
```js
import yada from 'yada'
```
To achive this, one just has to add a file to the root called `.prettierrc` with the following content
```yaml
semi: false
singleQuote: true
```
Then prettier will do the rest.

**Comment by ericwindmill** [comment]
I support for sure. Is this change in the WIP branch you have open?

**Comment by levino** [comment]
No, but I can make a PR for this.
