### ISSUE TITLE
Question: Are CSS Preprocessors (SASS/LESS) supported ???

### ISSUE THREAD

**Issue by shashankKeshava** [ericwindmill/gatsby-starter-docs#18]
Hi @ericwindmill,

Is CSS Preprossors such as SASS and LESS available??? I tried using but the build failed since no appropriate loaders are available. 

### Code:
```javascript 
import React, { Component } from "react";
import './about.scss'
class About extends Component {
  render() {
    return (
      <div className="about">
        <h1>
          Edit About component or pages/about.jsx to include your information.
        </h1>
      </div>
    );
  }
}

export default About;
```

### Error:
![screen shot 2018-04-17 at 5 50 26 pm](https://user-images.githubusercontent.com/15323807/38869307-e2dd309e-4267-11e8-9e18-03d4d43ca764.png)

**Comment by levino** [comment]
This starter uses [styled components](https://github.com/styled-components/styled-components)

They replace any scss or less stuff you might wanna introduce. So supporting another way of adding styles is out of scope of this starter, I would say because it is bad practice to mix the patterns.

**Comment by shashankKeshava** [comment]
Ok, thanks for the response

Thanks and Regards,
Shashank K
*P* *Every 3,000 sheets of paper costs us a tree. Don't print anything
unless it's really necessary. Save trees.*
