### ISSUE TITLE
Remove all traces of stylelint

### ISSUE THREAD

**Issue by zenflow** [ericwindmill/gatsby-starter-docs#20]
There are some traces of stylelint in this repo creating the impression that stylelint is used in the project when apparently it is not.

> I guess this is a leftover from the starter this starter was forked from. In order to avoid this kind of question in the future, all mention of stylelint should be purged from the source. 
> @Levino https://github.com/ericwindmill/gatsby-starter-docs/issues/5#issuecomment-380745387

**Comment by ericwindmill** [comment]
Fixed
