### ISSUE TITLE
Algolia search integration

### ISSUE THREAD

**Issue by ziyafenn** [ericwindmill/gatsby-starter-docs#36]
Hey guys. I guess everyone can do that manually but would be cool if [algolia free search](https://www.algolia.com/) would be available already built-in! 
There is already a [plugin](https://github.com/algolia/gatsby-plugin-algolia) for that.

Thanks for the template.

**Comment by levino** [comment]
I vote no.

**Comment by ericwindmill** [comment]
I vote no also, I'd prefer to keep the bundle size down
