### ISSUE TITLE
NPM install results in 720(!!) vulnerabilities.

### ISSUE THREAD

**Issue by KerimG** [ericwindmill/gatsby-starter-docs#38]
I mean, I use Gatsby to generate static files so it doesn't really matter but Jesus, this is by far the highest vulnerability count I've seen so far.

```
added 2151 packages from 1166 contributors and audited 29719 packages in 343.651s
found 720 vulnerabilities (603 low, 94 moderate, 21 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

The Gatsby tutorial repos have like 3-5 vulnerabilities. 

How can we fix this?

**Comment by levino** [comment]
How about ``run `npm audit fix` ``?

**Comment by KerimG** [comment]
Well, that was anticlimactic lol. Down to 3 vulnerabilities and 1 package update with breaking changes.

**Comment by levino** [comment]
Could you open a PR?

**Comment by KerimG** [comment]
With what exactly? Just the npm audit fix or the fix for the breaking changes?

**Comment by levino** [comment]
Preferably everything. I would say a good start are your local changes.
