### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by anandpotukuchi** [ericwindmill/gatsby-starter-docs#39]
Can we have a release for 1.0.0? Would be great because the current patch is broken.

**Comment by anandpotukuchi** [comment]
#38

**Comment by ericwindmill** [comment]
Can you provide more details about what's broken?

**Comment by anandpotukuchi** [comment]
Actually, I found out after a little snooping around, nithing's actually broken. but it would be great to have a release. Let's consider this resolved.
