### ISSUE TITLE
Table of contents items persist and duplicate

### ISSUE THREAD

**Issue by nicopresto** [ericwindmill/gatsby-starter-docs#4]
I'm having an issue with lessons in the table of contents list. When new lessons are created, deleted or renamed, I end up with duplicates and ghost listings.

To reproduce:

1. Build the starter
 `gatsby new gatsby-starter-docs https://github.com/ericwindmill/gatsby-starter-docs`

1. Duplicate a lesson and rename, e.g. lesson_five.md, then increment the lesson and chapter numbers in frontmatter

1. Delete a lesson, e.g. lesson_two.md

Outcome: 
![image](https://user-images.githubusercontent.com/480671/34692899-b9f86796-f48f-11e7-9bb6-540c80e24fcb.png)

Thoughts:

-  There is a warning about keys in the list items for TableOfContents.jsx
![image](https://user-images.githubusercontent.com/480671/34693118-8381f5fa-f490-11e7-82d6-756e3bc39dd9.png)

I tried to add keys but still had duplicate posts

`< li key={Math.random()}>`

and

`<li key={node.title()}>`

- I disabled offline access, but still had ghost listings

There is a relevant reference in Readme:

> Configured to auto generate documentation 'Table of Contents' - you just need to follow the file frontmatter conventions in the 'lessons' folder.

Are there any additional conventions or settings to consider?

**Comment by nicopresto** [comment]
This issue seems to be related to caching. When I wipe the ".cache" folder the table of contents (TOC) titles update, and deleted/duplicate titles are removed. The TOC does not seem to be hot reloading.

Could this be related to #1 (slow compilation time) i.e., is it possible that it is taking a long time to flush the cache? Upon relaunch with "gatsby develop" I'm getting times of:

`info bootstrap finished - 11.198 s`

Do we need to tweak the cache-control settings?
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/caching.md

**Comment by ericwindmill** [comment]
@nicopresto Just noticed this issue. As far as I can tell the best way adjust cache-control right now is with the netlify plugin, which doesn't seem like a good fix. I use Netlify, but not everyone does I imagine. Am I missing something?

**Comment by ericwindmill** [comment]
The ToC works completely different now, so closing.

**Comment by levino** [comment]
Changing the implementation of the TOC did not change the issue described by OP. Issue should be reopened imo.
