### ISSUE TITLE
Blog posts - no list, view is unstyled

### ISSUE THREAD

**Issue by rafi** [ericwindmill/gatsby-starter-docs#6]
I see a whole implementation you did for `./content/posts` but there isn't a list of posts anywhere, and when I've tried browsing to https://localhost:8000/post-one/ I got an awkward page with no styling.

**Comment by ericwindmill** [comment]
I don't consider this an issue. This template is set up to take blog posts, but its primarily meant for docs / ToC. I didn't want to make this too opinionated in styling -- just in functionality. 

I understand what you're saying, and I don't disagree that the post page could use some work, but this isn't meant to be an all inclusive WordPress-theme-like-situation.

**Comment by levino** [comment]
I think you should rather remove all `posts` related stuff. It is just confusing. Better remove it than leave this half working reminisence in there.

**Comment by ericwindmill** [comment]
Fixed.
