### ISSUE TITLE
Question: How to prevent component re-rendering while routing?

### ISSUE THREAD

**Issue by ajithr** [ericwindmill/gatsby-starter-docs#7]
HI @ericwindmill ,

I have tried to use my custom react component inside the left side pane, but while routing the custom component re-rendered. Can you please let me know how to prevent this behavior from my custom component or any other settings need to configure? Also can you let me know where the routing handled in this starters?

Thanks in advance...

**Comment by ericwindmill** [comment]
I'd need to see some code. BTW, I pretty much redid the whole table of contents system recently. So if you aren't on the new system -- it works much better.

**Comment by levino** [comment]
Yes. I second @ericwindmill on this. Please provide a working code example (fork this repo and add your component) and reopen the issue. Until then I vote for closing as "not reproducible".
